### ISSUE TITLE
<3 the scripts. But eth1?

### ISSUE THREAD

**Issue by cdrage** [dave-tucker/docker-network-demos#1]
Hey Dave!

Love being able to get multi-host networking setup. It's awesome.

I did however run into a few snags.

I'm using the --generic driver and each of my VPS' uses eth0 not eth1. I managed to get it working, but should we add a warning or at least a note to the user to use eth0 if you don't have two interfaces? Only reason being is that when docker-machine fails, it actually prevents the docker daemon from booting up again causing a looping `Cannot connect to the Docker daemon. Is the docker daemon running on this host?`

Thanks,

**Comment by dave-tucker** [comment]
Added readme in https://github.com/dave-tucker/docker-network-demos/commit/37a4e0a71ae45383be6e1ffd605e797bf289a050

Let me know if that's helps clear things up and I'll close the issue!
Glad you found these useful!

**Comment by cdrage** [comment]
@dave-tucker AWESOME! That helps a lot :) Thanks!
